// Code generated by "stringer -type=EdgeLabelEnum"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Open-0]
	_ = x[Closed-1]
	_ = x[Forbidden-2]
}

const _EdgeLabelEnum_name = "OpenClosedForbidden"

var _EdgeLabelEnum_index = [...]uint8{0, 4, 10, 19}

func (i EdgeLabelEnum) String() string {
	if i < 0 || i >= EdgeLabelEnum(len(_EdgeLabelEnum_index)-1) {
		return "EdgeLabelEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EdgeLabelEnum_name[_EdgeLabelEnum_index[i]:_EdgeLabelEnum_index[i+1]]
}
